### ISSUE TITLE
Unity NetworkManager Compatible?

### ISSUE THREAD

**Issue by stophboy7** [rempelj/unet-steamworks#1]
Is it possible to use your SteamNetworkManager in conjunction with Unity's NetworkManager in order to do things like change scenes?  I notice your sample project doesn't include a Unity NetworkManager.

**Comment by rempelj** [comment]
Yes it is possible. You can modify the SteamNetworkManager so that it is derived from the NetworkManager. 

If you do this you'll have to make some tweaks. The most important one being that SteamNetworkManager.Awake() has to be removed so that it doesn't override the Awake function in Unity's NetworkManager. You can move the contents of Awake into Start, or some other custom init function.

You may want to remove the networkPrefabs list and use the NetworkManager's SpawnInfo instead. 

There may be some other tweaks you need to do. It depends on your project. 

Hope that helps!

**Comment by rempelj** [comment]
I removed Awake() from SteamNetworkManager so that it can be derived from NetworkManager without errors.
